### ISSUE TITLE
Perhaps distribute using pip

### ISSUE THREAD

**Issue by hughsie** [cwerling/psptool#9]
I'm tempted to start using PSPTool in the LVFS to analyse AMD binaries. If it was installable using pip it would be much easier to deploy and keep updated.

**Comment by cwerling** [comment]
Done 🎉

**Comment by hughsie** [comment]
Many thanks! I'll give it a go in the next few days and tell you how I get on.

**Comment by hughsie** [comment]
I've created this tiny plugin -- https://github.com/fwupd/lvfs-website/pull/425 -- comments very welcome, thanks.

**Comment by cwerling** [comment]
I don't have any comments, your usage looks solid. Except that it feels great to see PSPTool being used by lvfs. Let me know when it's live. 🙂
